[package]
name = "img2webp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-multipart = "0.6.0"
actix-files = "0.6.2"
futures = "0.3.28"
image = "0.24.6"
tempfile = "3.5.0"
